name: Verify Gifs Filename

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Verify Gifs Filename
              run: |
                  npm install
                  npm run compile:test
                  npm run test:gifs
